-- INSERT INTO events values (	decode(encode('239','hex'),'hex')	,	LOWER('Ignition')	);
-- INSERT INTO events values (	decode(encode('240','hex'),'hex')	,	LOWER('Movement')	);
-- INSERT INTO events values (	decode(encode('80','hex'),'hex')	,	LOWER('Data Mode')	);
INSERT INTO events values (	decode(encode('21','hex'),'hex')	,	LOWER('GSM Signal')	);
INSERT INTO events values (	decode(encode('200','hex'),'hex')	,	LOWER('Sleep Mode')	);
INSERT INTO events values (	decode(encode('69','hex'),'hex')	,	LOWER('GNSS Status')	);
INSERT INTO events values (	decode(encode('181','hex'),'hex')	,	LOWER('GNSS PDOP')	);
INSERT INTO events values (	decode(encode('182','hex'),'hex')	,	LOWER('GNSS HDOP')	);
INSERT INTO events values (	decode(encode('24','hex'),'hex')	,	LOWER('Speed')	);
INSERT INTO events values (	decode(encode('205','hex'),'hex')	,	LOWER('GSM Cell ID')	);
INSERT INTO events values (	decode(encode('206','hex'),'hex')	,	LOWER('GSM Area Code')	);
INSERT INTO events values (	decode(encode('67','hex'),'hex')	,	LOWER('Battery Voltage')	);
INSERT INTO events values (	decode(encode('68','hex'),'hex')	,	LOWER('Battery Current')	);
INSERT INTO events values (	decode(encode('113','hex'),'hex')	,	LOWER('Battery Level')	);
INSERT INTO events values (	decode(encode('66','hex'),'hex')	,	LOWER('External Voltage')	);
INSERT INTO events values (	decode(encode('800','hex'),'hex')	,	LOWER('Extended External Voltage')	);
INSERT INTO events values (	decode(encode('241','hex'),'hex')	,	LOWER('Active GSM Operator')	);
INSERT INTO events values (	decode(encode('199','hex'),'hex')	,	LOWER('Trip Odometer')	);
INSERT INTO events values (	decode(encode('16','hex'),'hex')	,	LOWER('Total Odometer')	);
INSERT INTO events values (	decode(encode('1','hex'),'hex')	,	LOWER('Digital Input 1')	);
INSERT INTO events values (	decode(encode('841','hex'),'hex')	,	LOWER('DOUT 1 Overcurrent')	);
INSERT INTO events values (	decode(encode('842','hex'),'hex')	,	LOWER('DOUT2 Overcurrent')	);
INSERT INTO events values (	decode(encode('9','hex'),'hex')	,	LOWER('Analog Input 1')	);
INSERT INTO events values (	decode(encode('6','hex'),'hex')	,	LOWER('Analog Input 2')	);
INSERT INTO events values (	decode(encode('839','hex'),'hex')	,	LOWER('Extended Analog Input 1')	);
INSERT INTO events values (	decode(encode('840','hex'),'hex')	,	LOWER('Extended Analog Input 2')	);
INSERT INTO events values (	decode(encode('303','hex'),'hex')	,	LOWER('Instant Movement')	);
INSERT INTO events values (	decode(encode('17','hex'),'hex')	,	LOWER('Axis X')	);
INSERT INTO events values (	decode(encode('18','hex'),'hex')	,	LOWER('Axis Y')	);
INSERT INTO events values (	decode(encode('19','hex'),'hex')	,	LOWER('Axis Z')	);
INSERT INTO events values (	decode(encode('11','hex'),'hex')	,	LOWER('ICCID1')	);
INSERT INTO events values (	decode(encode('14','hex'),'hex')	,	LOWER('ICCID2')	);
INSERT INTO events values (	decode(encode('72','hex'),'hex')	,	LOWER('Dallas Temperature 1')	);
INSERT INTO events values (	decode(encode('73','hex'),'hex')	,	LOWER('Dallas Temperature 2')	);
INSERT INTO events values (	decode(encode('74','hex'),'hex')	,	LOWER('Dallas Temperature 3')	);
INSERT INTO events values (	decode(encode('75','hex'),'hex')	,	LOWER('Dallas Temperature 4')	);
INSERT INTO events values (	decode(encode('76','hex'),'hex')	,	LOWER('Dallas Temperature ID 1')	);
INSERT INTO events values (	decode(encode('77','hex'),'hex')	,	LOWER('Dallas Temperature ID 2')	);
INSERT INTO events values (	decode(encode('79','hex'),'hex')	,	LOWER('Dallas Temperature ID 3')	);
INSERT INTO events values (	decode(encode('71','hex'),'hex')	,	LOWER('Dallas Temperature ID 4')	);
INSERT INTO events values (	decode(encode('78','hex'),'hex')	,	LOWER('iButton')	);
INSERT INTO events values (	decode(encode('15','hex'),'hex')	,	LOWER('Eco Score')	);
INSERT INTO events values (	decode(encode('116','hex'),'hex')	,	LOWER('Charger Connected')	);
INSERT INTO events values (	decode(encode('854','hex'),'hex')	,	LOWER('User ID')	);
INSERT INTO events values (	decode(encode('387','hex'),'hex')	,	LOWER('ISO6709 Coordinates')	);
INSERT INTO events values (	decode(encode('288','hex'),'hex')	,	LOWER('GSM Cell ID 1')	);
INSERT INTO events values (	decode(encode('291','hex'),'hex')	,	LOWER('GSM Cell ID 2')	);
INSERT INTO events values (	decode(encode('294','hex'),'hex')	,	LOWER('GSM Cell ID 3')	);
INSERT INTO events values (	decode(encode('297','hex'),'hex')	,	LOWER('GSM Cell ID 4')	);
INSERT INTO events values (	decode(encode('287','hex'),'hex')	,	LOWER('GSM Cell LAC 1')	);
INSERT INTO events values (	decode(encode('290','hex'),'hex')	,	LOWER('GSM Cell LAC 2')	);
INSERT INTO events values (	decode(encode('293','hex'),'hex')	,	LOWER('GSM Cell LAC 3')	);
INSERT INTO events values (	decode(encode('296','hex'),'hex')	,	LOWER('GSM Cell LAC 4')	);
INSERT INTO events values (	decode(encode('1200','hex'),'hex')	,	LOWER('GSM Cell MNC 1')	);
INSERT INTO events values (	decode(encode('1201','hex'),'hex')	,	LOWER('GSM Cell MNC 2')	);
INSERT INTO events values (	decode(encode('1202','hex'),'hex')	,	LOWER('GSM Cell MNC 3')	);
INSERT INTO events values (	decode(encode('1203','hex'),'hex')	,	LOWER('GSM Cell MNC 4')	);
INSERT INTO events values (	decode(encode('286','hex'),'hex')	,	LOWER('GSM Signal RX 0')	);
INSERT INTO events values (	decode(encode('289','hex'),'hex')	,	LOWER('GSM Signal RX 1')	);
INSERT INTO events values (	decode(encode('292','hex'),'hex')	,	LOWER('GSM Signal RX 2')	);
INSERT INTO events values (	decode(encode('295','hex'),'hex')	,	LOWER('GSM Signal RX 3')	);
INSERT INTO events values (	decode(encode('298','hex'),'hex')	,	LOWER('GSM Signal RX 4')	);
INSERT INTO events values (	decode(encode('399','hex'),'hex')	,	LOWER('Time To First Fix')	);
INSERT INTO events values (	decode(encode('155','hex'),'hex')	,	LOWER('Geofence zone 01')	);
INSERT INTO events values (	decode(encode('156','hex'),'hex')	,	LOWER('Geofence zone 02')	);
INSERT INTO events values (	decode(encode('157','hex'),'hex')	,	LOWER('Geofence zone 03')	);
INSERT INTO events values (	decode(encode('158','hex'),'hex')	,	LOWER('Geofence zone 04')	);
INSERT INTO events values (	decode(encode('159','hex'),'hex')	,	LOWER('Geofence zone 05')	);
INSERT INTO events values (	decode(encode('61','hex'),'hex')	,	LOWER('Geofence zone 06')	);
INSERT INTO events values (	decode(encode('62','hex'),'hex')	,	LOWER('Geofence zone 07')	);
INSERT INTO events values (	decode(encode('63','hex'),'hex')	,	LOWER('Geofence zone 08')	);
INSERT INTO events values (	decode(encode('64','hex'),'hex')	,	LOWER('Geofence zone 09')	);
INSERT INTO events values (	decode(encode('65','hex'),'hex')	,	LOWER('Geofence zone 10')	);
INSERT INTO events values (	decode(encode('70','hex'),'hex')	,	LOWER('Geofence zone 11')	);
INSERT INTO events values (	decode(encode('88','hex'),'hex')	,	LOWER('Geofence zone 12')	);
INSERT INTO events values (	decode(encode('91','hex'),'hex')	,	LOWER('Geofence zone 13')	);
INSERT INTO events values (	decode(encode('92','hex'),'hex')	,	LOWER('Geofence zone 14')	);
INSERT INTO events values (	decode(encode('93','hex'),'hex')	,	LOWER('Geofence zone 15')	);
INSERT INTO events values (	decode(encode('94','hex'),'hex')	,	LOWER('Geofence zone 16')	);
INSERT INTO events values (	decode(encode('95','hex'),'hex')	,	LOWER('Geofence zone 17')	);
INSERT INTO events values (	decode(encode('96','hex'),'hex')	,	LOWER('Geofence zone 18')	);
INSERT INTO events values (	decode(encode('97','hex'),'hex')	,	LOWER('Geofence zone 19')	);
INSERT INTO events values (	decode(encode('98','hex'),'hex')	,	LOWER('Geofence zone 20')	);
INSERT INTO events values (	decode(encode('99','hex'),'hex')	,	LOWER('Geofence zone 21')	);
INSERT INTO events values (	decode(encode('153','hex'),'hex')	,	LOWER('Geofence zone 22')	);
INSERT INTO events values (	decode(encode('154','hex'),'hex')	,	LOWER('Geofence zone 23')	);
INSERT INTO events values (	decode(encode('190','hex'),'hex')	,	LOWER('Geofence zone 24')	);
INSERT INTO events values (	decode(encode('191','hex'),'hex')	,	LOWER('Geofence zone 25')	);
INSERT INTO events values (	decode(encode('192','hex'),'hex')	,	LOWER('Geofence zone 26')	);
INSERT INTO events values (	decode(encode('193','hex'),'hex')	,	LOWER('Geofence zone 27')	);
INSERT INTO events values (	decode(encode('194','hex'),'hex')	,	LOWER('Geofence zone 28')	);
INSERT INTO events values (	decode(encode('195','hex'),'hex')	,	LOWER('Geofence zone 29')	);
INSERT INTO events values (	decode(encode('196','hex'),'hex')	,	LOWER('Geofence zone 30')	);
INSERT INTO events values (	decode(encode('197','hex'),'hex')	,	LOWER('Geofence zone 31')	);
INSERT INTO events values (	decode(encode('198','hex'),'hex')	,	LOWER('Geofence zone 32')	);
INSERT INTO events values (	decode(encode('208','hex'),'hex')	,	LOWER('Geofence zone 33')	);
INSERT INTO events values (	decode(encode('209','hex'),'hex')	,	LOWER('Geofence zone 34')	);
INSERT INTO events values (	decode(encode('216','hex'),'hex')	,	LOWER('Geofence zone 35')	);
INSERT INTO events values (	decode(encode('217','hex'),'hex')	,	LOWER('Geofence zone 36')	);
INSERT INTO events values (	decode(encode('218','hex'),'hex')	,	LOWER('Geofence zone 37')	);
INSERT INTO events values (	decode(encode('219','hex'),'hex')	,	LOWER('Geofence zone 38')	);
INSERT INTO events values (	decode(encode('220','hex'),'hex')	,	LOWER('Geofence zone 39')	);
INSERT INTO events values (	decode(encode('221','hex'),'hex')	,	LOWER('Geofence zone 40')	);
INSERT INTO events values (	decode(encode('222','hex'),'hex')	,	LOWER('Geofence zone 41')	);
INSERT INTO events values (	decode(encode('223','hex'),'hex')	,	LOWER('Geofence zone 42')	);
INSERT INTO events values (	decode(encode('224','hex'),'hex')	,	LOWER('Geofence zone 43')	);
INSERT INTO events values (	decode(encode('225','hex'),'hex')	,	LOWER('Geofence zone 44')	);
INSERT INTO events values (	decode(encode('226','hex'),'hex')	,	LOWER('Geofence zone 45')	);
INSERT INTO events values (	decode(encode('227','hex'),'hex')	,	LOWER('Geofence zone 46')	);
INSERT INTO events values (	decode(encode('228','hex'),'hex')	,	LOWER('Geofence zone 47')	);
INSERT INTO events values (	decode(encode('229','hex'),'hex')	,	LOWER('Geofence zone 48')	);
INSERT INTO events values (	decode(encode('230','hex'),'hex')	,	LOWER('Geofence zone 49')	);
INSERT INTO events values (	decode(encode('231','hex'),'hex')	,	LOWER('Geofence zone 50')	);
INSERT INTO events values (	decode(encode('175','hex'),'hex')	,	LOWER('Auto Geofence')	);
INSERT INTO events values (	decode(encode('250','hex'),'hex')	,	LOWER('Trip')	);
INSERT INTO events values (	decode(encode('255','hex'),'hex')	,	LOWER('Overspeeding Event')	);
INSERT INTO events values (	decode(encode('251','hex'),'hex')	,	LOWER('Idling')	);
-- INSERT INTO events values (	decode(encode('252','hex'),'hex')	,	LOWER('Unplug')	);
INSERT INTO events values (	decode(encode('253','hex'),'hex')	,	LOWER('Green driving type')	);
INSERT INTO events values (	decode(encode('246','hex'),'hex')	,	LOWER('Towing')	);
INSERT INTO events values (	decode(encode('247','hex'),'hex')	,	LOWER('Crash detection')	);
INSERT INTO events values (	decode(encode('257','hex'),'hex')	,	LOWER('Crash trace data')	);
INSERT INTO events values (	decode(encode('248','hex'),'hex')	,	LOWER('Immobilizer')	);
INSERT INTO events values (	decode(encode('254','hex'),'hex')	,	LOWER('Green Driving Value')	);
INSERT INTO events values (	decode(encode('249','hex'),'hex')	,	LOWER('Jamming')	);
INSERT INTO events values (	decode(encode('243','hex'),'hex')	,	LOWER('Green driving event duration')	);
INSERT INTO events values (	decode(encode('236','hex'),'hex')	,	LOWER('Alarm')	);
INSERT INTO events values (	decode(encode('242','hex'),'hex')	,	LOWER('ManDown/FallDown')	);
INSERT INTO events values (	decode(encode('310','hex'),'hex')	,	LOWER('Movement Event')	);
INSERT INTO events values (	decode(encode('389','hex'),'hex')	,	LOWER('Button Click')	);
INSERT INTO events values (	decode(encode('390','hex'),'hex')	,	LOWER('Power Event')	);
INSERT INTO events values (	decode(encode('520','hex'),'hex')	,	LOWER('Tamper detection Event')	);
INSERT INTO events values (	decode(encode('386','hex'),'hex')	,	LOWER('Last Known Position')	);
INSERT INTO events values (	decode(encode('400','hex'),'hex')	,	LOWER('Amber Alert state')	);
INSERT INTO events values (	decode(encode('401','hex'),'hex')	,	LOWER('Amber Alert timer value')	);
INSERT INTO events values (	decode(encode('403','hex'),'hex')	,	LOWER('Heart Rate Alert')	);
-- INSERT INTO events values (	decode(encode('236','hex'),'hex')	,	LOWER('Alarm')	);
INSERT INTO events values (	decode(encode('20012','hex'),'hex')	,	LOWER('Recovery mode alarm')	);
INSERT INTO events values (	decode(encode('339','hex'),'hex')	,	LOWER('Serial number')	);
INSERT INTO events values (	decode(encode('340','hex'),'hex')	,	LOWER('Master control FW version[1]')	);
INSERT INTO events values (	decode(encode('341','hex'),'hex')	,	LOWER('Error')	);
INSERT INTO events values (	decode(encode('342','hex'),'hex')	,	LOWER('Alarm code')	);
INSERT INTO events values (	decode(encode('344','hex'),'hex')	,	LOWER('Lock status')	);
INSERT INTO events values (	decode(encode('345','hex'),'hex')	,	LOWER('Buzzer alarm status')	);
INSERT INTO events values (	decode(encode('346','hex'),'hex')	,	LOWER('External battery status')	);
INSERT INTO events values (	decode(encode('347','hex'),'hex')	,	LOWER('Charging status')	);
INSERT INTO events values (	decode(encode('349','hex'),'hex')	,	LOWER('Current operation mode')	);
INSERT INTO events values (	decode(encode('350','hex'),'hex')	,	LOWER('Internal battery voltage')	);
INSERT INTO events values (	decode(encode('351','hex'),'hex')	,	LOWER('External battery voltage')	);
INSERT INTO events values (	decode(encode('352','hex'),'hex')	,	LOWER('Battery percentage')	);
INSERT INTO events values (	decode(encode('353','hex'),'hex')	,	LOWER('Actual remaining mileage')	);
INSERT INTO events values (	decode(encode('354','hex'),'hex')	,	LOWER('Predicted remaining mileage')	);
INSERT INTO events values (	decode(encode('355','hex'),'hex')	,	LOWER('Speed')	);
INSERT INTO events values (	decode(encode('356','hex'),'hex')	,	LOWER('Total mileage')	);
INSERT INTO events values (	decode(encode('357','hex'),'hex')	,	LOWER('Single mileage')	);
INSERT INTO events values (	decode(encode('358','hex'),'hex')	,	LOWER('Total operation time')	);
INSERT INTO events values (	decode(encode('359','hex'),'hex')	,	LOWER('Total riding time')	);
INSERT INTO events values (	decode(encode('360','hex'),'hex')	,	LOWER('Single operation time')	);
INSERT INTO events values (	decode(encode('361','hex'),'hex')	,	LOWER('Single riding time')	);
INSERT INTO events values (	decode(encode('362','hex'),'hex')	,	LOWER('Body temperature')	);
INSERT INTO events values (	decode(encode('363','hex'),'hex')	,	LOWER('Internal battery temperature 1')	);
INSERT INTO events values (	decode(encode('364','hex'),'hex')	,	LOWER('Internal battery temperature 2')	);
INSERT INTO events values (	decode(encode('365','hex'),'hex')	,	LOWER('External battery temperature 1')	);
INSERT INTO events values (	decode(encode('366','hex'),'hex')	,	LOWER('Supply voltage')	);
INSERT INTO events values (	decode(encode('367','hex'),'hex')	,	LOWER('External battery temperature 2')	);
INSERT INTO events values (	decode(encode('369','hex'),'hex')	,	LOWER('Average speed')	);
INSERT INTO events values (	decode(encode('370','hex'),'hex')	,	LOWER('External battery FW version[1]')	);
INSERT INTO events values (	decode(encode('371','hex'),'hex')	,	LOWER('Internal battery FW version[1]')	);
INSERT INTO events values (	decode(encode('372','hex'),'hex')	,	LOWER('Instrument panel FW version[1]')	);
INSERT INTO events values (	decode(encode('374','hex'),'hex')	,	LOWER('Internal battery capacity')	);
INSERT INTO events values (	decode(encode('375','hex'),'hex')	,	LOWER('External battery capacity')	);
INSERT INTO events values (	decode(encode('392','hex'),'hex')	,	LOWER('Normal speed limit')	);
INSERT INTO events values (	decode(encode('393','hex'),'hex')	,	LOWER('Eco speed limit')	);
INSERT INTO events values (	decode(encode('394','hex'),'hex')	,	LOWER('Sport speed limit')	);
INSERT INTO events values (	decode(encode('396','hex'),'hex')	,	LOWER('Battery lock status')	);
INSERT INTO events values (	decode(encode('397','hex'),'hex')	,	LOWER('Cable lock Status')	);
INSERT INTO events values (	decode(encode('377','hex'),'hex')	,	LOWER('Cable lock FW version')	);
INSERT INTO events values (	decode(encode('801','hex'),'hex')	,	LOWER('Park Brake')	);
INSERT INTO events values (	decode(encode('802','hex'),'hex')	,	LOWER('Selected')	);
INSERT INTO events values (	decode(encode('803','hex'),'hex')	,	LOWER('Selected Charge Mode')	);
INSERT INTO events values (	decode(encode('804','hex'),'hex')	,	LOWER('Charger Voltage')	);
INSERT INTO events values (	decode(encode('805','hex'),'hex')	,	LOWER('Charger Current')	);
INSERT INTO events values (	decode(encode('806','hex'),'hex')	,	LOWER('Charger Control Mode')	);
INSERT INTO events values (	decode(encode('807','hex'),'hex')	,	LOWER('Charger BMS COM Timeout')	);
INSERT INTO events values (	decode(encode('808','hex'),'hex')	,	LOWER('Charger CRC Violation')	);
INSERT INTO events values (	decode(encode('809','hex'),'hex')	,	LOWER('Charger MC Violation')	);
INSERT INTO events values (	decode(encode('810','hex'),'hex')	,	LOWER('Charger Status')	);
INSERT INTO events values (	decode(encode('811','hex'),'hex')	,	LOWER('Charger Voltage Actual')	);
INSERT INTO events values (	decode(encode('812','hex'),'hex')	,	LOWER('Charger Internal Fault')	);
INSERT INTO events values (	decode(encode('813','hex'),'hex')	,	LOWER('Charger Energy')	);
INSERT INTO events values (	decode(encode('814','hex'),'hex')	,	LOWER('Charger Current Actual')	);
INSERT INTO events values (	decode(encode('815','hex'),'hex')	,	LOWER('Throttle Position')	);
INSERT INTO events values (	decode(encode('816','hex'),'hex')	,	LOWER('Brake Pressed')	);
INSERT INTO events values (	decode(encode('817','hex'),'hex')	,	LOWER('Charge Plug')	);
INSERT INTO events values (	decode(encode('818','hex'),'hex')	,	LOWER('Kill Switch Active')	);
INSERT INTO events values (	decode(encode('819','hex'),'hex')	,	LOWER('Kickstand Release')	);
INSERT INTO events values (	decode(encode('820','hex'),'hex')	,	LOWER('Powerstrain State')	);
INSERT INTO events values (	decode(encode('821','hex'),'hex')	,	LOWER('Malfunction Indicator')	);
INSERT INTO events values (	decode(encode('822','hex'),'hex')	,	LOWER('Current range')	);
INSERT INTO events values (	decode(encode('823','hex'),'hex')	,	LOWER('SoH Battery')	);
INSERT INTO events values (	decode(encode('824','hex'),'hex')	,	LOWER('SoC Battery')	);
INSERT INTO events values (	decode(encode('825','hex'),'hex')	,	LOWER('Vehicle available')	);
INSERT INTO events values (	decode(encode('826','hex'),'hex')	,	LOWER('Charging Active')	);
INSERT INTO events values (	decode(encode('827','hex'),'hex')	,	LOWER('Remaining Charge Time')	);
INSERT INTO events values (	decode(encode('828','hex'),'hex')	,	LOWER('Remaining Capacity')	);
INSERT INTO events values (	decode(encode('829','hex'),'hex')	,	LOWER('Full Charge Capacity')	);
INSERT INTO events values (	decode(encode('830','hex'),'hex')	,	LOWER('Driving direction')	);
INSERT INTO events values (	decode(encode('831','hex'),'hex')	,	LOWER('Drive Mode')	);
INSERT INTO events values (	decode(encode('832','hex'),'hex')	,	LOWER('Park Brake Active')	);
INSERT INTO events values (	decode(encode('833','hex'),'hex')	,	LOWER('Total Distance')	);
INSERT INTO events values (	decode(encode('834','hex'),'hex')	,	LOWER('Trip Distance')	);
INSERT INTO events values (	decode(encode('835','hex'),'hex')	,	LOWER('Vehicle speed')	);
INSERT INTO events values (	decode(encode('836','hex'),'hex')	,	LOWER('Ignition Status')	);
INSERT INTO events values (	decode(encode('837','hex'),'hex')	,	LOWER('Ignition Fast Status')	);
INSERT INTO events values (	decode(encode('838','hex'),'hex')	,	LOWER('Power Consumption')	);
INSERT INTO events values (	decode(encode('1121','hex'),'hex')	,	LOWER('CAN Unlocked')	);
INSERT INTO events values (	decode(encode('1122','hex'),'hex')	,	LOWER('BMS2 Temperature Current Max')	);
INSERT INTO events values (	decode(encode('1123','hex'),'hex')	,	LOWER('BMS2 Temperature Current Min')	);
INSERT INTO events values (	decode(encode('1124','hex'),'hex')	,	LOWER('BMS2 Voltage Cell Min')	);
INSERT INTO events values (	decode(encode('1125','hex'),'hex')	,	LOWER('BMS2 Voltage Cell Max')	);
INSERT INTO events values (	decode(encode('1100','hex'),'hex')	,	LOWER('BMS0 Temperature Current Max')	);
INSERT INTO events values (	decode(encode('1101','hex'),'hex')	,	LOWER('BMS0 Temperature Current Min')	);
INSERT INTO events values (	decode(encode('11002','hex'),'hex')	,	LOWER('BMS0 Voltage Cell Min')	);
INSERT INTO events values (	decode(encode('11003','hex'),'hex')	,	LOWER('BMS0 Voltage Cell Max')	);
INSERT INTO events values (	decode(encode('1104','hex'),'hex')	,	LOWER('BMS1 Temperature Current Max')	);
INSERT INTO events values (	decode(encode('1105','hex'),'hex')	,	LOWER('BMS1 Temperature Current Min')	);
INSERT INTO events values (	decode(encode('1106','hex'),'hex')	,	LOWER('BMS1 Voltage Cell Min')	);
INSERT INTO events values (	decode(encode('1107','hex'),'hex')	,	LOWER('BMS1 Voltage Cell Max')	);
-- INSERT INTO events values (	decode(encode('804','hex'),'hex')	,	LOWER('Charger Voltage')	);
-- INSERT INTO events values (	decode(encode('821','hex'),'hex')	,	LOWER('Malfunction Indicator')	);
-- INSERT INTO events values (	decode(encode('822','hex'),'hex')	,	LOWER('Current range')	);
-- INSERT INTO events values (	decode(encode('824','hex'),'hex')	,	LOWER('SoC Battery')	);
-- INSERT INTO events values (	decode(encode('828','hex'),'hex')	,	LOWER('Remaining Capacity')	);
-- INSERT INTO events values (	decode(encode('833','hex'),'hex')	,	LOWER('Total Distance')	);
-- INSERT INTO events values (	decode(encode('835','hex'),'hex')	,	LOWER('Vehicle speed')	);
-- INSERT INTO events values (	decode(encode('837','hex'),'hex')	,	LOWER('Ignition Fast Status')	);
-- INSERT INTO events values (	decode(encode('843','hex'),'hex')	,	LOWER('Helmet Status')	);
-- INSERT INTO events values (	decode(encode('844','hex'),'hex')	,	LOWER('Top Case Sensor')	);
INSERT INTO events values (	decode(encode('845','hex'),'hex')	,	LOWER('Central Stand Up')	);
INSERT INTO events values (	decode(encode('846','hex'),'hex')	,	LOWER('Emergency')	);
INSERT INTO events values (	decode(encode('847','hex'),'hex')	,	LOWER('Over-Under Temperature')	);
INSERT INTO events values (	decode(encode('848','hex'),'hex')	,	LOWER('Regeneration Disabled')	);
INSERT INTO events values (	decode(encode('849','hex'),'hex')	,	LOWER('Battery On/Off')	);
INSERT INTO events values (	decode(encode('850','hex'),'hex')	,	LOWER('Warning UnderVoltage')	);
INSERT INTO events values (	decode(encode('851','hex'),'hex')	,	LOWER('Warning OverVoltage')	);
INSERT INTO events values (	decode(encode('852','hex'),'hex')	,	LOWER('Warning OverCurrent')	);
INSERT INTO events values (	decode(encode('853','hex'),'hex')	,	LOWER('Warning Short Circuit')	);
INSERT INTO events values (	decode(encode('900','hex'),'hex')	,	LOWER('Manual CAN 0')	);
INSERT INTO events values (	decode(encode('901','hex'),'hex')	,	LOWER('Manual CAN 1')	);
INSERT INTO events values (	decode(encode('902','hex'),'hex')	,	LOWER('Manual CAN 2')	);
INSERT INTO events values (	decode(encode('903','hex'),'hex')	,	LOWER('Manual CAN 3')	);
INSERT INTO events values (	decode(encode('904','hex'),'hex')	,	LOWER('Manual CAN 4')	);
INSERT INTO events values (	decode(encode('905','hex'),'hex')	,	LOWER('Manual CAN 5')	);
INSERT INTO events values (	decode(encode('906','hex'),'hex')	,	LOWER('Manual CAN 6')	);
INSERT INTO events values (	decode(encode('907','hex'),'hex')	,	LOWER('Manual CAN 7')	);
INSERT INTO events values (	decode(encode('908','hex'),'hex')	,	LOWER('Manual CAN 8')	);
INSERT INTO events values (	decode(encode('909','hex'),'hex')	,	LOWER('Manual CAN 9')	);
INSERT INTO events values (	decode(encode('910','hex'),'hex')	,	LOWER('Manual CAN 10')	);
INSERT INTO events values (	decode(encode('911','hex'),'hex')	,	LOWER('Manual CAN 11')	);
INSERT INTO events values (	decode(encode('912','hex'),'hex')	,	LOWER('Manual CAN 12')	);
INSERT INTO events values (	decode(encode('913','hex'),'hex')	,	LOWER('Manual CAN 13')	);
INSERT INTO events values (	decode(encode('914','hex'),'hex')	,	LOWER('Manual CAN 14')	);
INSERT INTO events values (	decode(encode('915','hex'),'hex')	,	LOWER('Manual CAN 15')	);
INSERT INTO events values (	decode(encode('916','hex'),'hex')	,	LOWER('Manual CAN 16')	);
INSERT INTO events values (	decode(encode('917','hex'),'hex')	,	LOWER('Manual CAN 17')	);
INSERT INTO events values (	decode(encode('918','hex'),'hex')	,	LOWER('Manual CAN 18')	);
INSERT INTO events values (	decode(encode('919','hex'),'hex')	,	LOWER('Manual CAN 19')	);
INSERT INTO events values (	decode(encode('920','hex'),'hex')	,	LOWER('Manual CAN 20')	);
INSERT INTO events values (	decode(encode('921','hex'),'hex')	,	LOWER('Manual CAN 21')	);
INSERT INTO events values (	decode(encode('922','hex'),'hex')	,	LOWER('Manual CAN 22')	);
INSERT INTO events values (	decode(encode('923','hex'),'hex')	,	LOWER('Manual CAN 23')	);
INSERT INTO events values (	decode(encode('924','hex'),'hex')	,	LOWER('Manual CAN 24')	);
INSERT INTO events values (	decode(encode('925','hex'),'hex')	,	LOWER('Manual CAN 25')	);
INSERT INTO events values (	decode(encode('926','hex'),'hex')	,	LOWER('Manual CAN 26')	);
INSERT INTO events values (	decode(encode('927','hex'),'hex')	,	LOWER('Manual CAN 27')	);
INSERT INTO events values (	decode(encode('928','hex'),'hex')	,	LOWER('Manual CAN 28')	);
INSERT INTO events values (	decode(encode('929','hex'),'hex')	,	LOWER('Manual CAN 29')	);
INSERT INTO events values (	decode(encode('930','hex'),'hex')	,	LOWER('Accelerator Pedal 1 Low Idle Switch')	);
INSERT INTO events values (	decode(encode('931','hex'),'hex')	,	LOWER('Accelerator Pedal Kickdown Switch')	);
INSERT INTO events values (	decode(encode('932','hex'),'hex')	,	LOWER('Road Speed Limit Status')	);
INSERT INTO events values (	decode(encode('933','hex'),'hex')	,	LOWER('Accelerator Pedal 2 Low Idle Switch')	);
INSERT INTO events values (	decode(encode('934','hex'),'hex')	,	LOWER('Accelerator Pedal Position 1')	);
INSERT INTO events values (	decode(encode('936','hex'),'hex')	,	LOWER('Engine Percent Load At Current Speed')	);
INSERT INTO events values (	decode(encode('937','hex'),'hex')	,	LOWER('Remote Accelerator Pedal Position')	);
INSERT INTO events values (	decode(encode('938','hex'),'hex')	,	LOWER('Accelerator Pedal 2 Position')	);
INSERT INTO events values (	decode(encode('939','hex'),'hex')	,	LOWER('Vehicle Acceleration Rate Limit Status')	);
INSERT INTO events values (	decode(encode('940','hex'),'hex')	,	LOWER('Momentary Engine Maximum Power Enable Feedback')	);
INSERT INTO events values (	decode(encode('941','hex'),'hex')	,	LOWER('DPF Thermal Management Active')	);
INSERT INTO events values (	decode(encode('942','hex'),'hex')	,	LOWER('SCR Thermal Management Active')	);
INSERT INTO events values (	decode(encode('943','hex'),'hex')	,	LOWER('Actual Maximum Available Engine - Percent Torque')	);
INSERT INTO events values (	decode(encode('944','hex'),'hex')	,	LOWER('Estimated Pumping - Percent Torque')	);
INSERT INTO events values (	decode(encode('945','hex'),'hex')	,	LOWER('Engine Torque Mode')	);
INSERT INTO events values (	decode(encode('946','hex'),'hex')	,	LOWER('Actual Engine - Percent Torque (Fractional)')	);
INSERT INTO events values (	decode(encode('947','hex'),'hex')	,	LOWER('Driver’s Demand Engine - Percent Torque')	);
INSERT INTO events values (	decode(encode('948','hex'),'hex')	,	LOWER('Actual Engine - Percent Torque')	);
INSERT INTO events values (	decode(encode('949','hex'),'hex')	,	LOWER('Engine Speed')	);
INSERT INTO events values (	decode(encode('950','hex'),'hex')	,	LOWER('Source Address of Controlling Device for Engine Control')	);
INSERT INTO events values (	decode(encode('951','hex'),'hex')	,	LOWER('Engine Starter Mode')	);
INSERT INTO events values (	decode(encode('952','hex'),'hex')	,	LOWER('Engine Demand – Percent Torque')	);
INSERT INTO events values (	decode(encode('953','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Intake Temperature')	);
INSERT INTO events values (	decode(encode('954','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Outlet Temperature')	);
INSERT INTO events values (	decode(encode('955','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Differential Pressure')	);
INSERT INTO events values (	decode(encode('956','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Intake Temperature Preliminary FMI')	);
INSERT INTO events values (	decode(encode('957','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Outlet Temperature Preliminary FMI')	);
INSERT INTO events values (	decode(encode('958','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Oxidation Catalyst Differential Pressure Preliminary FMI')	);
INSERT INTO events values (	decode(encode('959','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Soot Load Percent')	);
INSERT INTO events values (	decode(encode('960','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Ash Load Percent')	);
INSERT INTO events values (	decode(encode('961','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration')	);
INSERT INTO events values (	decode(encode('962','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold')	);
INSERT INTO events values (	decode(encode('963','hex'),'hex')	,	LOWER('Aftertreatment 1 Exhaust Temperature 2')	);
INSERT INTO events values (	decode(encode('964','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Intermediate Temperature')	);
INSERT INTO events values (	decode(encode('965','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Differential Pressure')	);
INSERT INTO events values (	decode(encode('966','hex'),'hex')	,	LOWER('Aftertreatment 1 Exhaust Temperature 2 Preliminary FMI')	);
INSERT INTO events values (	decode(encode('967','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Differential Pressure Preliminary FMI')	);
INSERT INTO events values (	decode(encode('968','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Intermediate Temperature Preliminary FMI')	);
INSERT INTO events values (	decode(encode('969','hex'),'hex')	,	LOWER('Aftertreatment 1 Exhaust Temperature 1')	);
INSERT INTO events values (	decode(encode('970','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Intake Temperature')	);
INSERT INTO events values (	decode(encode('971','hex'),'hex')	,	LOWER('Aftertreatment 1 Exhaust Temperature 1 Preliminary FMI')	);
INSERT INTO events values (	decode(encode('972','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Intake Temperature Preliminary FMI')	);
INSERT INTO events values (	decode(encode('973','hex'),'hex')	,	LOWER('Trip Fuel (Gaseous)')	);
INSERT INTO events values (	decode(encode('974','hex'),'hex')	,	LOWER('Total Fuel Used (Gaseous)')	);
INSERT INTO events values (	decode(encode('989','hex'),'hex')	,	LOWER('Trip Vehicle Distance')	);
INSERT INTO events values (	decode(encode('990','hex'),'hex')	,	LOWER('Total Vehicle Distance')	);
INSERT INTO events values (	decode(encode('991','hex'),'hex')	,	LOWER('Engine Total Hours of Operation')	);
INSERT INTO events values (	decode(encode('992','hex'),'hex')	,	LOWER('Engine Total Revolutions')	);
INSERT INTO events values (	decode(encode('993','hex'),'hex')	,	LOWER('Total Vehicle Hours')	);
INSERT INTO events values (	decode(encode('994','hex'),'hex')	,	LOWER('Total Power Takeoff Hours')	);
INSERT INTO events values (	decode(encode('995','hex'),'hex')	,	LOWER('Engine Trip Fuel')	);
INSERT INTO events values (	decode(encode('996','hex'),'hex')	,	LOWER('Engine Total Fuel Used')	);
INSERT INTO events values (	decode(encode('1002','hex'),'hex')	,	LOWER('Engine Coolant Temperature')	);
INSERT INTO events values (	decode(encode('1003','hex'),'hex')	,	LOWER('Engine Fuel 1 Temperature 1')	);
INSERT INTO events values (	decode(encode('1004','hex'),'hex')	,	LOWER('Engine Oil Temperature 1')	);
INSERT INTO events values (	decode(encode('1005','hex'),'hex')	,	LOWER('Engine Turbocharger 1 Oil Temperature')	);
INSERT INTO events values (	decode(encode('1006','hex'),'hex')	,	LOWER('Engine Intercooler Temperature')	);
INSERT INTO events values (	decode(encode('1007','hex'),'hex')	,	LOWER('Engine Charge Air Cooler Thermostat Opening')	);
INSERT INTO events values (	decode(encode('1008','hex'),'hex')	,	LOWER('Engine Fuel Delivery Pressure')	);
INSERT INTO events values (	decode(encode('1009','hex'),'hex')	,	LOWER('Engine Extended Crankcase Blow-by Pressure')	);
INSERT INTO events values (	decode(encode('1010','hex'),'hex')	,	LOWER('Engine Oil Level')	);
INSERT INTO events values (	decode(encode('1011','hex'),'hex')	,	LOWER('Engine Oil Pressure 1')	);
INSERT INTO events values (	decode(encode('1012','hex'),'hex')	,	LOWER('Engine Crankcase Pressure 1')	);
INSERT INTO events values (	decode(encode('1013','hex'),'hex')	,	LOWER('Engine Coolant Pressure 1')	);
INSERT INTO events values (	decode(encode('1014','hex'),'hex')	,	LOWER('Engine Coolant Level 1')	);
INSERT INTO events values (	decode(encode('1015','hex'),'hex')	,	LOWER('Two Speed Axle Switch')	);
INSERT INTO events values (	decode(encode('1016','hex'),'hex')	,	LOWER('Two Speed Axle Switch')	);
INSERT INTO events values (	decode(encode('1017','hex'),'hex')	,	LOWER('Cruise Control Pause Switch')	);
INSERT INTO events values (	decode(encode('1018','hex'),'hex')	,	LOWER('Park Brake Release Inhibit Request')	);
INSERT INTO events values (	decode(encode('1019','hex'),'hex')	,	LOWER('Wheel-Based Vehicle Speed')	);
INSERT INTO events values (	decode(encode('1020','hex'),'hex')	,	LOWER('Cruise Control Active')	);
INSERT INTO events values (	decode(encode('1021','hex'),'hex')	,	LOWER('Cruise Control Enable Switch')	);
INSERT INTO events values (	decode(encode('1022','hex'),'hex')	,	LOWER('Brake Switch')	);
INSERT INTO events values (	decode(encode('1023','hex'),'hex')	,	LOWER('Clutch Switch')	);
INSERT INTO events values (	decode(encode('1024','hex'),'hex')	,	LOWER('Cruise Control Set Switch')	);
INSERT INTO events values (	decode(encode('1025','hex'),'hex')	,	LOWER('Cruise Control Coast (Decelerate) Switch')	);
INSERT INTO events values (	decode(encode('1026','hex'),'hex')	,	LOWER('Cruise Control Resume Switch')	);
INSERT INTO events values (	decode(encode('1027','hex'),'hex')	,	LOWER('Cruise Control Accelerate Switch')	);
INSERT INTO events values (	decode(encode('1028','hex'),'hex')	,	LOWER('Cruise Control Set Speed')	);
INSERT INTO events values (	decode(encode('1029','hex'),'hex')	,	LOWER('PTO Governor State')	);
INSERT INTO events values (	decode(encode('1030','hex'),'hex')	,	LOWER('Cruise Control States')	);
INSERT INTO events values (	decode(encode('1031','hex'),'hex')	,	LOWER('Engine Idle Increment Switch')	);
INSERT INTO events values (	decode(encode('1032','hex'),'hex')	,	LOWER('Engine Idle Decrement Switch')	);
INSERT INTO events values (	decode(encode('1033','hex'),'hex')	,	LOWER('Engine Diagnostic Test Mode Switch')	);
INSERT INTO events values (	decode(encode('1034','hex'),'hex')	,	LOWER('Engine Shutdown Override Switch')	);
INSERT INTO events values (	decode(encode('1035','hex'),'hex')	,	LOWER('Engine Fuel Rate')	);
INSERT INTO events values (	decode(encode('1036','hex'),'hex')	,	LOWER('Engine Instantaneous Fuel Economy')	);
INSERT INTO events values (	decode(encode('1037','hex'),'hex')	,	LOWER('Engine Average Fuel Economy')	);
INSERT INTO events values (	decode(encode('1038','hex'),'hex')	,	LOWER('Engine Throttle Valve 1 Position 1')	);
INSERT INTO events values (	decode(encode('1039','hex'),'hex')	,	LOWER('Engine Throttle Valve 2 Position')	);
INSERT INTO events values (	decode(encode('1040','hex'),'hex')	,	LOWER('Barometric Pressure')	);
INSERT INTO events values (	decode(encode('1041','hex'),'hex')	,	LOWER('Cab Interior Temperature')	);
INSERT INTO events values (	decode(encode('1042','hex'),'hex')	,	LOWER('Ambient Air Temperature')	);
INSERT INTO events values (	decode(encode('1043','hex'),'hex')	,	LOWER('Engine Intake 1 Air Temperature')	);
INSERT INTO events values (	decode(encode('1044','hex'),'hex')	,	LOWER('Road Surface Temperature')	);
INSERT INTO events values (	decode(encode('1045','hex'),'hex')	,	LOWER('Aftertreatment 1 Diesel Particulate Filter Intake Pressure')	);
INSERT INTO events values (	decode(encode('1046','hex'),'hex')	,	LOWER('Engine Intake Manifold #1 Pressure')	);
INSERT INTO events values (	decode(encode('1047','hex'),'hex')	,	LOWER('Engine Intake Manifold 1 Temperature')	);
INSERT INTO events values (	decode(encode('1048','hex'),'hex')	,	LOWER('Engine Intake Air Pressure')	);
INSERT INTO events values (	decode(encode('1049','hex'),'hex')	,	LOWER('Engine Air Filter 1 Differential Pressure')	);
INSERT INTO events values (	decode(encode('1050','hex'),'hex')	,	LOWER('Engine Exhaust Temperature')	);
INSERT INTO events values (	decode(encode('1051','hex'),'hex')	,	LOWER('Engine Coolant Filter Differential Pressure')	);
INSERT INTO events values (	decode(encode('1052','hex'),'hex')	,	LOWER('SLI Battery 1 Net Current')	);
INSERT INTO events values (	decode(encode('1053','hex'),'hex')	,	LOWER('Alternator Current')	);
INSERT INTO events values (	decode(encode('1054','hex'),'hex')	,	LOWER('Charging System Potential (Voltage)')	);
INSERT INTO events values (	decode(encode('1055','hex'),'hex')	,	LOWER('Battery Potential / Power Input 1')	);
INSERT INTO events values (	decode(encode('1056','hex'),'hex')	,	LOWER('Key Switch Battery Potential')	);
INSERT INTO events values (	decode(encode('1057','hex'),'hex')	,	LOWER('Transmission Clutch 1 Pressure')	);
INSERT INTO events values (	decode(encode('1058','hex'),'hex')	,	LOWER('Transmission Oil Level 1')	);
INSERT INTO events values (	decode(encode('1059','hex'),'hex')	,	LOWER('Transmission Filter Differential Pressure')	);
INSERT INTO events values (	decode(encode('1060','hex'),'hex')	,	LOWER('Transmission 1 Oil Pressure')	);
INSERT INTO events values (	decode(encode('1061','hex'),'hex')	,	LOWER('Transmission Oil Temperature 1')	);
INSERT INTO events values (	decode(encode('1062','hex'),'hex')	,	LOWER('Transmission Oil Level 1 High / Low')	);
INSERT INTO events values (	decode(encode('1063','hex'),'hex')	,	LOWER('Transmission Oil Level 1 Countdown Timer')	);
INSERT INTO events values (	decode(encode('1064','hex'),'hex')	,	LOWER('Transmission Oil Level 1 Measurement Status')	);
INSERT INTO events values (	decode(encode('1065','hex'),'hex')	,	LOWER('Washer Fluid Level')	);
INSERT INTO events values (	decode(encode('1066','hex'),'hex')	,	LOWER('Fuel Level 1')	);
INSERT INTO events values (	decode(encode('1067','hex'),'hex')	,	LOWER('Engine Fuel Filter Differential Pressure')	);
INSERT INTO events values (	decode(encode('1068','hex'),'hex')	,	LOWER('Engine Oil Filter Differential Pressure')	);
INSERT INTO events values (	decode(encode('1069','hex'),'hex')	,	LOWER('Cargo Ambient Temperature')	);
INSERT INTO events values (	decode(encode('1070','hex'),'hex')	,	LOWER('Fuel Level 2')	);
INSERT INTO events values (	decode(encode('1071','hex'),'hex')	,	LOWER('Engine Oil Filter Differential Pressure (Extended Range)')	);
INSERT INTO events values (	decode(encode('815','hex'),'hex')	,	LOWER('Throttle Position')	);
INSERT INTO events values (	decode(encode('816','hex'),'hex')	,	LOWER('Brake Pressed')	);
INSERT INTO events values (	decode(encode('817','hex'),'hex')	,	LOWER('Charge Plug')	);
INSERT INTO events values (	decode(encode('818','hex'),'hex')	,	LOWER('Kill Switch Active')	);
INSERT INTO events values (	decode(encode('819','hex'),'hex')	,	LOWER('Kickstand Release')	);
INSERT INTO events values (	decode(encode('820','hex'),'hex')	,	LOWER('Powerstrain State')	);
INSERT INTO events values (	decode(encode('821','hex'),'hex')	,	LOWER('Malfunction Indicator')	);
INSERT INTO events values (	decode(encode('822','hex'),'hex')	,	LOWER('Current range')	);
INSERT INTO events values (	decode(encode('824','hex'),'hex')	,	LOWER('SoC Battery')	);
INSERT INTO events values (	decode(encode('828','hex'),'hex')	,	LOWER('Remaining Capacity')	);
INSERT INTO events values (	decode(encode('829','hex'),'hex')	,	LOWER('Full Charge Capacity')	);
INSERT INTO events values (	decode(encode('831','hex'),'hex')	,	LOWER('Drive Mode')	);
INSERT INTO events values (	decode(encode('833','hex'),'hex')	,	LOWER('Total Distance')	);
INSERT INTO events values (	decode(encode('835','hex'),'hex')	,	LOWER('Vehicle speed')	);
INSERT INTO events values (	decode(encode('836','hex'),'hex')	,	LOWER('Ignition Status')	);
INSERT INTO events values (	decode(encode('844','hex'),'hex')	,	LOWER('Top Case Sensor')	);
-- INSERT INTO events values (	decode(encode('1126','hex'),'hex')	,	LOWER('Max Available Power')	);
-- INSERT INTO events values (	decode(encode('1127','hex'),'hex')	,	LOWER('Handlebar Lock')	);
-- INSERT INTO events values (	decode(encode('1128','hex'),'hex')	,	LOWER('Rear Brake Pressed')	);
INSERT INTO events values (	decode(encode('1129','hex'),'hex')	,	LOWER('COM Error')	);
INSERT INTO events values (	decode(encode('1130','hex'),'hex')	,	LOWER('RPM')	);
INSERT INTO events values (	decode(encode('1131','hex'),'hex')	,	LOWER('Torque Current')	);
INSERT INTO events values (	decode(encode('1132','hex'),'hex')	,	LOWER('SN High')	);
INSERT INTO events values (	decode(encode('1133','hex'),'hex')	,	LOWER('SN Low')	);
INSERT INTO events values (	decode(encode('1134','hex'),'hex')	,	LOWER('Lowest Battery Voltage')	);
INSERT INTO events values (	decode(encode('1135','hex'),'hex')	,	LOWER('Lowest Battery ID')	);
INSERT INTO events values (	decode(encode('1136','hex'),'hex')	,	LOWER('Highest Battery Voltage')	);
INSERT INTO events values (	decode(encode('1137','hex'),'hex')	,	LOWER('Highest Battery ID')	);
INSERT INTO events values (	decode(encode('1138','hex'),'hex')	,	LOWER('Highest Mismatch Voltage')	);
INSERT INTO events values (	decode(encode('1139','hex'),'hex')	,	LOWER('Highest Mismatch ID')	);
INSERT INTO events values (	decode(encode('1140','hex'),'hex')	,	LOWER('Lowest Battery Temperature')	);
INSERT INTO events values (	decode(encode('1141','hex'),'hex')	,	LOWER('Lowest Temperature Battery ID')	);
INSERT INTO events values (	decode(encode('1142','hex'),'hex')	,	LOWER('Highest Battery Temperature')	);
INSERT INTO events values (	decode(encode('1143','hex'),'hex')	,	LOWER('Highest Temperature Battery ID')	);
INSERT INTO events values (	decode(encode('1144','hex'),'hex')	,	LOWER('Time To Full Load')	);
INSERT INTO events values (	decode(encode('1145','hex'),'hex')	,	LOWER('Time To Empty')	);
INSERT INTO events values (	decode(encode('1146','hex'),'hex')	,	LOWER('Time To Full')	);
INSERT INTO events values (	decode(encode('1147','hex'),'hex')	,	LOWER('Cluster State')	);
INSERT INTO events values (	decode(encode('1148','hex'),'hex')	,	LOWER('Cluster SoC')	);
INSERT INTO events values (	decode(encode('1149','hex'),'hex')	,	LOWER('Max Discharge Current')	);
INSERT INTO events values (	decode(encode('1150','hex'),'hex')	,	LOWER('Recuperation Allowed')	);
INSERT INTO events values (	decode(encode('1151','hex'),'hex')	,	LOWER('Switch Process Needed')	);
INSERT INTO events values (	decode(encode('1152','hex'),'hex')	,	LOWER('SoC Switch Level')	);
INSERT INTO events values (	decode(encode('1153','hex'),'hex')	,	LOWER('Part Charge Capacity')	);
INSERT INTO events values (	decode(encode('1154','hex'),'hex')	,	LOWER('Cluster Voltage')	);
INSERT INTO events values (	decode(encode('1155','hex'),'hex')	,	LOWER('Cluster Current')	);
INSERT INTO events values (	decode(encode('1156','hex'),'hex')	,	LOWER('Major Version')	);
INSERT INTO events values (	decode(encode('1157','hex'),'hex')	,	LOWER('Minor Version')	);
INSERT INTO events values (	decode(encode('1158','hex'),'hex')	,	LOWER('Patch Version')	);
INSERT INTO events values (	decode(encode('1159','hex'),'hex')	,	LOWER('Recognized Batteries')	);
INSERT INTO events values (	decode(encode('1160','hex'),'hex')	,	LOWER('Activated Batteries')	);
INSERT INTO events values (	decode(encode('1161','hex'),'hex')	,	LOWER('Faulty Batteries')	);
INSERT INTO events values (	decode(encode('1162','hex'),'hex')	,	LOWER('Battery 1 Voltage')	);
INSERT INTO events values (	decode(encode('1163','hex'),'hex')	,	LOWER('Battery 1 Current')	);
INSERT INTO events values (	decode(encode('1164','hex'),'hex')	,	LOWER('Battery 1 State')	);
INSERT INTO events values (	decode(encode('1165','hex'),'hex')	,	LOWER('Battery 1 SoC')	);
INSERT INTO events values (	decode(encode('1166','hex'),'hex')	,	LOWER('Battery 1 Temperature 1')	);
INSERT INTO events values (	decode(encode('1167','hex'),'hex')	,	LOWER('Battery 1 Temperature 2')	);
INSERT INTO events values (	decode(encode('1168','hex'),'hex')	,	LOWER('Battery 1 Power Stage Temp')	);
INSERT INTO events values (	decode(encode('1169','hex'),'hex')	,	LOWER('Battery 1 Remaining Capacity')	);
INSERT INTO events values (	decode(encode('1170','hex'),'hex')	,	LOWER('Battery 2 Voltage')	);
INSERT INTO events values (	decode(encode('1171','hex'),'hex')	,	LOWER('Battery 2 Current')	);
INSERT INTO events values (	decode(encode('1172','hex'),'hex')	,	LOWER('Battery 2 State')	);
INSERT INTO events values (	decode(encode('1173','hex'),'hex')	,	LOWER('Battery 2 SoC')	);
INSERT INTO events values (	decode(encode('1174','hex'),'hex')	,	LOWER('Battery 2 Temperature 1')	);
INSERT INTO events values (	decode(encode('1175','hex'),'hex')	,	LOWER('Battery 2 Temperature 2')	);
INSERT INTO events values (	decode(encode('1176','hex'),'hex')	,	LOWER('Battery 2 Power Stage Temp')	);
INSERT INTO events values (	decode(encode('1177','hex'),'hex')	,	LOWER('Battery 2 Remaining Capacity')	);
INSERT INTO events values (	decode(encode('1178','hex'),'hex')	,	LOWER('Battery ID 0 Error Code')	);
INSERT INTO events values (	decode(encode('1179','hex'),'hex')	,	LOWER('Battery ID 1 Error Code')	);
INSERT INTO events values (	decode(encode('1180','hex'),'hex')	,	LOWER('Cluster Error Code')	);
INSERT INTO events values (	decode(encode('1181','hex'),'hex')	,	LOWER('Max Charge Current')	);
INSERT INTO events values (	decode(encode('1182','hex'),'hex')	,	LOWER('Lowest Battery 2 Temperature')	);
INSERT INTO events values (	decode(encode('1183','hex'),'hex')	,	LOWER('Highest Battery 2 Temperature')	);
INSERT INTO events values (	decode(encode('1184','hex'),'hex')	,	LOWER('Lowest Battery 2 Voltage')	);
INSERT INTO events values (	decode(encode('1185','hex'),'hex')	,	LOWER('Highest Battery 2 Voltage')	);
INSERT INTO events values (	decode(encode('855','hex'),'hex')	,	LOWER('Power')	);
INSERT INTO events values (	decode(encode('856','hex'),'hex')	,	LOWER('Current Trip Range')	);
INSERT INTO events values (	decode(encode('857','hex'),'hex')	,	LOWER('Total Trip Range')	);
INSERT INTO events values (	decode(encode('858','hex'),'hex')	,	LOWER('Battery Capacity')	);
INSERT INTO events values (	decode(encode('859','hex'),'hex')	,	LOWER('Low Voltage')	);
INSERT INTO events values (	decode(encode('860','hex'),'hex')	,	LOWER('High Temperature')	);
INSERT INTO events values (	decode(encode('861','hex'),'hex')	,	LOWER('Upload Time')	);
INSERT INTO events values (	decode(encode('862','hex'),'hex')	,	LOWER('Moving Abnormal')	);
INSERT INTO events values (	decode(encode('863','hex'),'hex')	,	LOWER('Range')	);
INSERT INTO events values (	decode(encode('864','hex'),'hex')	,	LOWER('Lock Status')	);
INSERT INTO events values (	decode(encode('865','hex'),'hex')	,	LOWER('Vehicle FW version')	);
INSERT INTO events values (	decode(encode('866','hex'),'hex')	,	LOWER('Total Range')	);
INSERT INTO events values (	decode(encode('867','hex'),'hex')	,	LOWER('Battery Energy')	);
INSERT INTO events values (	decode(encode('868','hex'),'hex')	,	LOWER('Power System Error')	);
INSERT INTO events values (	decode(encode('869','hex'),'hex')	,	LOWER('Power Train Error')	);
INSERT INTO events values (	decode(encode('870','hex'),'hex')	,	LOWER('Instrument System Error')	);
INSERT INTO events values (	decode(encode('25','hex'),'hex')	,	LOWER('BLE Temperature #1')	);
INSERT INTO events values (	decode(encode('26','hex'),'hex')	,	LOWER('BLE Temperature #2')	);
INSERT INTO events values (	decode(encode('27','hex'),'hex')	,	LOWER('BLE Temperature #3')	);
INSERT INTO events values (	decode(encode('28','hex'),'hex')	,	LOWER('BLE Temperature #4')	);
INSERT INTO events values (	decode(encode('29','hex'),'hex')	,	LOWER('BLE Battery #1')	);
INSERT INTO events values (	decode(encode('20','hex'),'hex')	,	LOWER('BLE Battery #2')	);
INSERT INTO events values (	decode(encode('22','hex'),'hex')	,	LOWER('BLE Battery #3')	);
INSERT INTO events values (	decode(encode('23','hex'),'hex')	,	LOWER('BLE Battery #4')	);
INSERT INTO events values (	decode(encode('86','hex'),'hex')	,	LOWER('BLE Humidity #1')	);
INSERT INTO events values (	decode(encode('104','hex'),'hex')	,	LOWER('BLE Humidity #2')	);
INSERT INTO events values (	decode(encode('106','hex'),'hex')	,	LOWER('BLE Humidity #3')	);
INSERT INTO events values (	decode(encode('108','hex'),'hex')	,	LOWER('BLE Humidity #4')	);
INSERT INTO events values (	decode(encode('331','hex'),'hex')	,	LOWER('BLE 1 Custom #1')	);
INSERT INTO events values (	decode(encode('463','hex'),'hex')	,	LOWER('BLE 1 Custom #2')	);
INSERT INTO events values (	decode(encode('464','hex'),'hex')	,	LOWER('BLE 1 Custom #3')	);
INSERT INTO events values (	decode(encode('465','hex'),'hex')	,	LOWER('BLE 1 Custom #4')	);
INSERT INTO events values (	decode(encode('466','hex'),'hex')	,	LOWER('BLE 1 Custom #5')	);
INSERT INTO events values (	decode(encode('332','hex'),'hex')	,	LOWER('BLE 2 Custom #1')	);
INSERT INTO events values (	decode(encode('467','hex'),'hex')	,	LOWER('BLE 2 Custom #2')	);
INSERT INTO events values (	decode(encode('468','hex'),'hex')	,	LOWER('BLE 2 Custom #3')	);
INSERT INTO events values (	decode(encode('469','hex'),'hex')	,	LOWER('BLE 2 Custom #4')	);
INSERT INTO events values (	decode(encode('470','hex'),'hex')	,	LOWER('BLE 2 Custom #5')	);
INSERT INTO events values (	decode(encode('333','hex'),'hex')	,	LOWER('BLE 3 Custom #1')	);
INSERT INTO events values (	decode(encode('471','hex'),'hex')	,	LOWER('BLE 3 Custom #2')	);
INSERT INTO events values (	decode(encode('472','hex'),'hex')	,	LOWER('BLE 3 Custom #3')	);
INSERT INTO events values (	decode(encode('473','hex'),'hex')	,	LOWER('BLE 3 Custom #4')	);
INSERT INTO events values (	decode(encode('474','hex'),'hex')	,	LOWER('BLE 3 Custom #5')	);
INSERT INTO events values (	decode(encode('334','hex'),'hex')	,	LOWER('BLE 4 Custom #1')	);
INSERT INTO events values (	decode(encode('475','hex'),'hex')	,	LOWER('BLE 4 Custom #2')	);
INSERT INTO events values (	decode(encode('476','hex'),'hex')	,	LOWER('BLE 4 Custom #3')	);
INSERT INTO events values (	decode(encode('477','hex'),'hex')	,	LOWER('BLE 4 Custom #4')	);
INSERT INTO events values (	decode(encode('478','hex'),'hex')	,	LOWER('BLE 4 Custom #5')	);
INSERT INTO events values (	decode(encode('385','hex'),'hex')	,	LOWER('Beacon ID(s)')	);
INSERT INTO events values (	decode(encode('874','hex'),'hex')	,	LOWER('Bluetooth Home Zone Violation state')	);
INSERT INTO events values (	decode(encode('889','hex'),'hex')	,	LOWER('Proximity Violation state')	);
INSERT INTO events values (	decode(encode('875','hex'),'hex')	,	LOWER('Proximity violation source with Teltonika devices')	);
INSERT INTO events values (	decode(encode('876','hex'),'hex')	,	LOWER('Proximity violation source with iBeacons')	);
INSERT INTO events values (	decode(encode('890','hex'),'hex')	,	LOWER('Proximity duration')	);
INSERT INTO events values (	decode(encode('891','hex'),'hex')	,	LOWER('BLE MAC address')	);
INSERT INTO events values (	decode(encode('263','hex'),'hex')	,	LOWER('BT Status')	);
INSERT INTO events values (	decode(encode('871','hex'),'hex')	,	LOWER('BLE Lock Status')	);
INSERT INTO events values (	decode(encode('872','hex'),'hex')	,	LOWER('BLE Lock Battery')	);
INSERT INTO events values (	decode(encode('873','hex'),'hex')	,	LOWER('BLE Lock Discovered')	);

INSERT INTO events values (	decode(encode('2','hex'),'hex')	,	LOWER('Digital Input 2')	);
INSERT INTO events values (	decode(encode('179','hex'),'hex')	,	LOWER('Digital Output 1')	);

INSERT INTO events values (	decode(encode('449','hex'),'hex')	,	LOWER('Ignition On Counter')	);

INSERT INTO events values (	decode(encode('498','hex'),'hex')	,	LOWER('Front camera state ')	);
INSERT INTO events values (	decode(encode('497','hex'),'hex')	,	LOWER('Rear camera state ')	);
